export const MAX_LENGTH_FOR_SIEVE = 2**32; // max bits allocatable can be therotically 2**33, improve it using a matrix of 2**33 * 2**33, but it crash due to other max values, or just need more than 8GB RAM.
export const MAX_NODE_ARRAY_LENGTH = 125813764;
export const EXCEL_MAX_ROWS = 1048576;
export const EXCEL_MAX_COLS = 16384;
export const MAX_DIGITS_SIEVE = 10;
export const MAX_DISPLAY_SIEVE = 10;
export const MAX_DIGITS_TRIPLE = 60000;
export const MAX_DIGITS_FACTORIZATION = 19;
export const MAX_SERIES_DIFFERENCES_SIZE = 20;
export const MAX_PRIME_LIST_NODE_MEMORY_SIZE = 433358473 - 1;                                           
export const MAX_SIEVE_VALUE_MEMORY_CRASH = 4755123800;                                    